### ISSUE TITLE
ESRGAN issue... ??

### ISSUE THREAD

**Issue by gateway** [rkhamilton/vqgan-clip-generator#58]
Ok I have never seen this before but I was running an image though my art types and the Real-ESRGAN got to about 85% and then barfed out with this error.. 

```
Real-ESRGAN:  85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                         | 28/33 [00:39<00:07,  1.40s/image]
Traceback (most recent call last):
  File "C:\Users\stiet\Desktop\Work\AIStuff\VQGAN\single_image.py", line 86, in <module>
    esrgan.inference_realesrgan(input=generated_images_path,
  File "C:\Users\stiet\anaconda3\envs\vqgan1\lib\site-packages\vqgan_clip\esrgan.py", line 99, in inference_realesrgan
    if len(img.shape) == 3 and img.shape[2] == 4:
AttributeError: 'NoneType' object has no attribute 'shape'
```
code
```
if upscale_images:
    esrgan.inference_realesrgan(input=generated_images_path,
                                output_images_path=upscaled_video_frames_path,
                                face_enhance=face_enhance,
                                purge_existing_files=True,
                                netscale=4,
                                outscale=4)
```

Im running the latest package...

**Comment by rkhamilton** [comment]
That reads to me that it didn't open a valid image file. This is all code I copied from Real-ESRGAN and made tweaks to, so I had to look into what's happening here.

My guess is that it ran into a file in the input folder that cv2 couldn't open for some reason. cv2.imread will not throw an error if it fails to open a file, it will just happily give you an empty variable which will cause the failure you saw. I added an error check in v2.2.2, which is now live. It will throw an error if it doesn't open a file successfully, which should help you troubleshoot. Let me know if you still see the error.

**Comment by gateway** [comment]
Ran it again this morning with the updated package.. 


Ok not sure why its failing on a specific image.. I mean I'm not doing anything to it.. 

```
Real-ESRGAN:  85%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                        | 29/34 [00:01<00:00, 18.78image/s]
Traceback (most recent call last):
  File "C:\Users\stiet\Desktop\Work\AIStuff\VQGAN\single_image.py", line 86, in <module>
    esrgan.inference_realesrgan(input=generated_images_path,
  File "C:\Users\stiet\anaconda3\envs\vqgan1\lib\site-packages\vqgan_clip\esrgan.py", line 108, in inference_realesrgan
    raise ValueError(f'file could not be read as a valid image.')
ValueError: file could not be read as a valid image.
PS C:\Users\stiet\Desktop\Work\AIStuff\VQGAN> 
```

**Comment by gateway** [comment]
Found the issue.. It was in one of the names of my art types that created a filename with a special chr in it.. 

dragon-Trompe L’oeil.png so I guess it barfs on that, ill have to do some string sanitizing or just make sure those types of chrs are not in my text prompts :) 

For my web app I used sanitize_filename https://pypi.org/project/sanitize-filename/

Anyhow thanks for adding in the error text, I finally was able to sit down and see where the image stopped..
